Simplify code and weak self everywhere
Important: not tested, might introduce bugs
Exception: extension for NineAnimator in Models/Anime.swift is using [unowned self]